name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run tests with Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99
          mvn clean test
